### PR TITLE
Regina margherita

### PR DESCRIPTION
**Pull request by alxekb**
So, let's merge this baby and share the joy of pizza with the world! 

# Remember, when it comes to pizza, we don't mess around. 🍕🙌

P.S. Don't forget to bring your appetite to the code review!

### CODE REVIEW

**Comment by alxekb** [comment]
Hey @tobiasrohloff,

I hope you're doing well. I wanted to bring your attention to my pull request that requires your review. While I've made progress on it, there is still some work left to be done. Unfortunately, I ran out of time to complete it before the deadline.

I would greatly appreciate it if you could take a look at the pull request and provide your valuable feedback.

Thank you so much for taking the time to review it. Have a fantastic day!

Best regards,
Aleksei

**Comment by tobiasrohloff** [comment]
Hey @alxekb,

many thanks for your submission. Sorry for the delay, GitHub somehow didn't send me an email notification like usual. You'll get feedback by the end of the week!

**Comment by tobiasrohloff** [comment]
Hey @alxekb,

I looked over your submission. Unfortunately, since the requirements are not fully implemented (especially the price calculation), I can't really evaluate it. We don't have a hard deadline, so do you want to keep working on it? Just let me know.

Completeness and quality are more important to me than rushing. Especially the "What we are looking for" section in the challenge description gives you good hints for the evaluation criteria.

**Comment by alxekb** [comment]
Thanks @tobiasrohloff for the feedback. I'll do it for sure 🫡

**Comment by alxekb** [comment]
I noticed that the price calculation is currently not persisted in the orders of your project, as mentioned in the provided GitHub link. 

To ensure a better understanding, could you please clarify where you would like to display the price in the user interface (UI)? I think it'll be fine if I'll show a pizza's price before adding it to the order and display total amount for the order as well. 

Additionally, it would be helpful to know how you would like to incorporate the price into the Order entity.

**Comment by tobiasrohloff** [comment]
It's totally up to you if you persist the total price or calculate it on the fly when requesting the corresponding route. Overall, we don't specify how you want to structure, store, or not store the data - or technical decisions in general.

The total price is visible in the provided mockup which also gives you good reference examples. You don't need to add any further functionality other than the illustrated and described ones.

**Comment by alxekb** [comment]
> It's totally up to you if you persist in the total price or calculate it on the fly when requesting the corresponding route. Overall, we don't specify how you want to structure, store, or not store the data - or technical decisions in general.
> 
> The total price is visible in the provided mockup which also gives you good reference examples. You don't need to add any further functionality other than the illustrated and described ones.

Got it. Price looks like a method since it is omitted in orders.json. Thanks @tobiasrohloff for the clarification, will work on it this afternoon. :)

**Comment by tobiasrohloff** [comment]
Hey @alxekb, any update on this? If you need more time, just let me know.

**Comment by alxekb** [comment]
> Hey @alxekb, any update on this? If you need more time, just let me know.

Yesterday I built decorator but didn't finished price promotions. Have not pushed anything new yet. I'll keep you updated when I got this app working @tobiasrohloff 😀

**Comment by alxekb** [comment]
@tobiasrohloff 

I wanted to provide you with an update regarding the current status of the project. Unfortunately, I have encountered some difficulties while trying to set up the runner. 

Thank you for your understanding and patience during this phase.

**Comment by tobiasrohloff** [comment]
Hey @alxekb, please don't spend too much time on the whole setup. I'm totally fine running a good old rails server. The explicit requirements and expectations of the challenge are much more important.

**Comment by alxekb** [comment]
> Hey @alxekb, please don't spend too much time on the whole setup. I'm totally fine running a good old rails server. The explicit requirements and expectations of the challenge are much more important.

I think you can take a look on it. The whole thing works well, specs are green (but runner is not) 🚀

@tobiasrohloff

**Pull request closed without merging**
